Replace hard coded location protocol "https" with the one derived fro…
cerner/jwala pull request #105
Opened 2017-05-15 19:06 UTC by jeddcuison

2017-05-19 15:44 UTC, jmahmoodcc requested changes
Just a question about how the protocol is derived

2017-05-19 15:44 UTC, jmahmoodcc commented on jwala-webapp/src/main/webapp/resources/js/react/group-operations/WebServerControlPanelWidget.js
> +                if (protocol.indexOf(WebServerControlPanelWidget.HTTP_PROTOCOL) > -1) {
Since this is testing for "http:", isn't it possible that "https" won't be returned either if the location.protocol is "http" too?

2017-05-22 15:20 UTC, LinHungWu commented
What is the default value if there is nothing to derived to?

2017-05-22 18:53 UTC, jeddcuison commented on jwala-webapp/src/main/webapp/resources/js/react/group-operations/WebServerControlPanelWidget.js
> +                if (protocol.indexOf(WebServerControlPanelWidget.HTTP_PROTOCOL) > -1) {
Good catch! I changed the code.

2017-05-22 19:18 UTC, jeddcuison commented
Answer to @LinHungWu's question "What is the default value if there is nothing to derived to?"

As discussed with @akinny, the default is "http:"

2017-05-22 19:40 UTC, akinny commented on jwala-webapp/src/main/webapp/resources/js/react/group-operations/WebServerControlPanelWidget.js
> +        let port = locationProtocol === WebServerControlPanelWidget.HTTP_PROTOCOL ? this.props.data.port :
shouldn't this.props.data.port be
this.props.data.httpPort?

2017-05-22 20:08 UTC, akinny approved these changes

2017-05-22 20:48 UTC, merged