REST Resources API to handle conditions being case insensitive
cerner/jwala pull request #127
Opened 2017-06-05 13:31 UTC by Sharvaribarve

Changed named queries to handle queries in case insensitive way

Before you contribute, please review these guidelines to help ensure a smooth process for everyone.

Thanks.

* Read [how to properly contribute to open source projects on Github][1].
* Fork the project.
* Use a feature branch.
* Write [good commit messages][2].
* Use the same coding conventions as the rest of the project.
* Commit locally and push to your fork until you are happy with your contribution.
* Make sure to add tests and verify all the tests are passing when merging upstream.
* Add an entry to the [Changelog][3] accordingly.
* Please add your name to the [CONTRIBUTORS.md][7] file. Adding your name to the [CONTRIBUTORS.md][7] file signifies agreement to all rights and reservations provided by the [License][4].
* [Squash related commits together][5].
* Open a [pull request][6].
* The pull request will be reviewed by the community and merged by the project committers.

[1]: http://gun.io/blog/how-to-github-fork-branch-and-pull-request
[2]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[3]: ./CHANGELOG.md
[4]: ./LICENSE
[5]: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
[6]: https://help.github.com/articles/using-pull-requests
[7]: ./CONTRIBUTORS.md

2017-06-05 14:14 UTC, PeterTeunissen approved these changes

2017-06-07 17:47 UTC, jmahmoodcc requested changes
Looks good, just some minor formatting changes. I'm sure you used the auto-formatter but it looks like it broke up a bunch of the queries in strange places. Readability counts!

2017-06-07 17:47 UTC, jmahmoodcc commented on jwala-persistence/src/main/java/com/cerner/jwala/persistence/jpa/domain/JpaApplicationConfigTemplate.java
> +                        " " +
Clean up this empty line

2017-06-07 17:47 UTC, jmahmoodcc commented on jwala-persistence/src/main/java/com/cerner/jwala/persistence/jpa/domain/JpaApplicationConfigTemplate.java
> +                query = "UPDATE JpaApplicationConfigTemplate t SET t.templateContent = :templateContent WHERE LOWER(t" +
Don't break up this variable across lines

2017-06-07 17:47 UTC, jmahmoodcc commented on jwala-persistence/src/main/java/com/cerner/jwala/persistence/jpa/domain/JpaApplicationConfigTemplate.java
> +                query = "SELECT t FROM JpaApplicationConfigTemplate t where t.templateName = :tempName and LOWER(t" +
Don't break up this variable across lines

2017-06-07 17:47 UTC, jmahmoodcc commented on jwala-persistence/src/main/java/com/cerner/jwala/persistence/jpa/domain/JpaApplicationConfigTemplate.java
> +                query = "DELETE FROM JpaApplicationConfigTemplate t WHERE t.templateName = :templateName AND LOWER(t" +
Don't break up this variable across lines

2017-06-07 17:47 UTC, jmahmoodcc commented on jwala-persistence/src/main/java/com/cerner/jwala/persistence/jpa/domain/JpaApplicationConfigTemplate.java
> +                query = "SELECT t FROM JpaApplicationConfigTemplate t where LOWER(t.app.name) = LOWER(:appName) and t" +
Don't break up this variable across lines

2017-06-07 17:47 UTC, jmahmoodcc commented on jwala-persistence/src/main/java/com/cerner/jwala/persistence/jpa/domain/resource/config/template/JpaGroupAppConfigTemplate.java
> +                query = "UPDATE JpaGroupAppConfigTemplate t SET t.templateContent = :templateContent WHERE LOWER(t" +
Don't break up this variable across lines

2017-06-07 17:47 UTC, jmahmoodcc commented on jwala-persistence/src/main/java/com/cerner/jwala/persistence/jpa/domain/resource/config/template/JpaGroupJvmConfigTemplate.java
> +                query = "UPDATE JpaGroupJvmConfigTemplate t SET t.templateContent = :templateContent WHERE LOWER(t" +
Don't break up this variable across lines

2017-06-07 17:47 UTC, jmahmoodcc commented on jwala-persistence/src/main/java/com/cerner/jwala/persistence/jpa/domain/resource/config/template/JpaGroupJvmConfigTemplate.java
> +                query = "DELETE FROM JpaGroupJvmConfigTemplate t WHERE t.templateName = :templateName AND LOWER(t.grp" +
Don't break up this variable across lines

2017-06-07 17:47 UTC, jmahmoodcc commented on jwala-persistence/src/main/java/com/cerner/jwala/persistence/jpa/domain/resource/config/template/JpaGroupJvmConfigTemplate.java
> +                query = "SELECT t FROM JpaGroupJvmConfigTemplate t where LOWER(t.grp.name) = LOWER(:grpName) and t" +
Don't break up this variable across lines

2017-06-07 17:47 UTC, jmahmoodcc commented on jwala-persistence/src/main/java/com/cerner/jwala/persistence/jpa/domain/resource/config/template/JpaGroupWebServerConfigTemplate.java
> +                "SELECT t.templateName FROM JpaGroupWebServerConfigTemplate t WHERE LOWER(t.grp.name) = LOWER" +
Don't break up this variable across lines

2017-06-07 17:47 UTC, jmahmoodcc commented on jwala-persistence/src/main/java/com/cerner/jwala/persistence/jpa/domain/resource/config/template/JpaGroupWebServerConfigTemplate.java
> +                        "and t" +
Don't break up this variable across lines

2017-06-07 17:47 UTC, jmahmoodcc commented on jwala-persistence/src/main/java/com/cerner/jwala/persistence/jpa/domain/resource/config/template/JpaJvmConfigTemplate.java
> +                query = "SELECT t.templateContent FROM JpaJvmConfigTemplate t where LOWER(t.jvm.name) = LOWER" +
Don't break up this variable across lines

2017-06-07 17:47 UTC, jmahmoodcc commented on jwala-persistence/src/main/java/com/cerner/jwala/persistence/jpa/domain/resource/config/template/JpaJvmConfigTemplate.java
> +                query = "UPDATE JpaJvmConfigTemplate t SET t.templateContent = :templateContent WHERE LOWER(t.jvm" +
Don't break up this variable across lines

2017-06-07 17:47 UTC, jmahmoodcc commented on jwala-persistence/src/main/java/com/cerner/jwala/persistence/jpa/domain/resource/config/template/JpaWebServerConfigTemplate.java
> +                query = "UPDATE JpaWebServerConfigTemplate t SET t.templateContent = :templateContent WHERE LOWER(t" +
Don't break up this variable across lines

2017-06-07 17:47 UTC, jmahmoodcc commented on jwala-persistence/src/main/java/com/cerner/jwala/persistence/jpa/domain/resource/config/template/JpaWebServerConfigTemplate.java
> +                    query="DELETE FROM JpaWebServerConfigTemplate t WHERE t.templateName = :templateName AND LOWER(t" +
Don't break up this variable across lines

2017-06-07 17:47 UTC, jmahmoodcc commented on jwala-persistence/src/main/java/com/cerner/jwala/persistence/jpa/domain/resource/config/template/JpaWebServerConfigTemplate.java
> +                query="DELETE FROM JpaWebServerConfigTemplate t WHERE t.templateName IN :templateNameList AND LOWER(t" +
Don't break up this variable across lines

2017-06-07 17:47 UTC, jmahmoodcc commented on jwala-persistence/src/main/java/com/cerner/jwala/persistence/jpa/domain/resource/config/template/JpaWebServerConfigTemplate.java
> +                query = "SELECT t FROM JpaWebServerConfigTemplate t WHERE t.templateName = :templateName AND LOWER(t" +
Don't break up this variable across lines

2017-06-07 17:48 UTC, jmahmoodcc commented
Make sure to run the postman tests on your build just to make sure all the query changes were done correctly.

2017-06-07 21:34 UTC, jmahmoodcc approved these changes

2017-06-07 21:34 UTC, merged