Cucumber selenium test cases for resources
cerner/jwala pull request #146
Opened 2017-07-12 17:44 UTC by rahulsayini

2017-07-13 14:45 UTC, Sharvaribarve requested changes

2017-07-13 14:45 UTC, Sharvaribarve commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/ManageResourceRunSteps.java
> +        jwalaUi.sleep();
Remove this, it is meant only during creating test cases and not in final test steps,  see the comment above the method in JwalaUI

2017-07-13 14:45 UTC, Sharvaribarve commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/ManageResourceRunSteps.java
> +        jwalaUi.sleep();
Remove this, it is meant only during creating test cases and not in final test steps, see the comment above the method in JwalaUI

2017-07-13 14:45 UTC, Sharvaribarve commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/ManageResourceRunSteps.java
> +        jwalaUi.sleep();
Remove this, it is meant only during creating test cases and not in final test steps, see the comment above the method in JwalaUI

2017-07-13 14:45 UTC, Sharvaribarve commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/ManageResourceRunSteps.java
> +        jwalaUi.sleep();
Remove this, it is meant only during creating test cases and not in final test steps, see the comment above the method in JwalaUI

2017-07-13 14:45 UTC, Sharvaribarve commented on jwala-integration-test/src/test/resources/com/cerner/jwala/ui/selenium/configuration/uploadJvmResource.feature
> +    Then check resource uploaded successful
Add more test cases, especially testing the hierarchy

2017-07-21 04:11 UTC, Sharvaribarve commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/OperationRunSteps.java
> +    @And("I wait for component (.*) state \"(.*)\"$")
Use backslashes like for other variables, or it will cause the variable to be in double quotes

2017-07-21 13:50 UTC, Sharvaribarve commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/OperationRunSteps.java
> +        jwalaUi.waitUntilElementIsVisible(By.xpath("//tr/td[text()='" + component + "']//following-sibling::td[6]/div/span[contains(text(),'" + status + "')"));
Square brackets are not balanced, need a square after contains span status

2017-07-27 15:44 UTC, jeddcuison requested changes
Please see my comments

2017-07-27 15:44 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/configuration/ManageJvmResourceTest.java
> + * Created by RS045609 on 7/10/2017.
Change RS045609 to your name

2017-07-27 15:44 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/CommonRunSteps.java
> +    @Given("I created a webserver with following parameters:$")
Please add ^

2017-07-27 15:44 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/CommonRunSteps.java
> +    @Given("I created a jvm with following parameters:$")
Please add ^

2017-07-27 15:44 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/CommonRunSteps.java
> +    @Given("I created a webapp with following parameters:$")
Please add ^

2017-07-27 15:44 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/ManageResourceRunSteps.java
> +    @Then("check resource uploaded successful")
Add the ^ and the $ e.g. 

    @Then("^check resource uploaded successful$")

2017-07-27 15:44 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/OperationRunSteps.java
> +    @And("I generate all webservers")
Add the ^ and the $ e.g.

    @And("^blah blah blah. . .$")

2017-07-27 15:44 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/OperationRunSteps.java
> +    @And("I generate all jvms")
Add the ^ and the $ e.g.

    @And("^blah blah blah. . .$")

2017-07-27 15:44 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/OperationRunSteps.java
> +    @And("I start all webservers")
Add the ^ and the $ e.g.

    @And("^blah blah blah. . .$")

2017-07-27 15:44 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/OperationRunSteps.java
> +    @And("I start all jvms")
Add the ^ and the $ e.g.

    @And("^blah blah blah. . .$")

2017-07-27 15:44 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/OperationRunSteps.java
> +    @And("I expanded group \"(.*)\"$")
Add the ^ e.g.

    @And("^blah blah blah. . .$")

2017-07-27 15:44 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/OperationRunSteps.java
> +    @And("I wait for popup string \"(.*)\"$")
Add the ^ e.g.

    @And("^blah blah blah. . .$")

2017-07-27 15:44 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/OperationRunSteps.java
> +    @And("I wait for component (.*) state \"(.*)\"$")
Add the ^

    @And("^blah blah blah. . .$")

2017-07-27 15:44 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/OperationRunSteps.java
> +    @And("I generate webapp")
Add the ^ and the $ e.g.

    @And("^blah blah blah. . .$")

2017-07-27 15:44 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/OperationRunSteps.java
> +    @And("I click on ok button")
Add the ^ and the $ e.g.

    @And("^blah blah blah. . .$")

2017-07-27 15:44 UTC, jeddcuison commented on jwala-integration-test/src/test/resources/com/cerner/jwala/ui/selenium/configuration/generateAndDeployResources.feature
> +    And I click the upload resource dialog ok button
We might be able to get away without a "when" but we should follow Cucumber scenario best practices and follow Given-When-Then for consistency

2017-07-27 15:44 UTC, jeddcuison commented on jwala-integration-test/src/test/resources/com/cerner/jwala/ui/selenium/configuration/generateAndDeployResources.feature
> +    Then check resource uploaded successful
Just use "And" since you already used "Then" on top

2017-07-27 15:44 UTC, jeddcuison commented on jwala-integration-test/src/test/resources/com/cerner/jwala/ui/selenium/configuration/uploadJvmResource.feature
> +    Then check resource uploaded successful
We might be able to get away without a "when" but we should follow Cucumber scenario best practices and follow Given-When-Then for consistency

2017-07-27 15:44 UTC, jeddcuison commented on jwala-integration-test/src/test/resources/com/cerner/jwala/ui/selenium/configuration/uploadWebappResource.feature
> +    And I click the upload resource dialog ok button
We might be able to get away without a "when" but we should follow Cucumber scenario best practices and follow Given-When-Then for consistency

2017-07-27 15:44 UTC, jeddcuison commented on jwala-integration-test/src/test/resources/com/cerner/jwala/ui/selenium/configuration/uploadWebserverResource.feature
> +    And I click the upload resource dialog ok button
We might be able to get away without a "when" but we should follow Cucumber scenario best practices and follow Given-When-Then for consistency

2017-07-27 18:05 UTC, Sharvaribarve commented
The hostName issue must be taken care of where a generic hostName is given.

2017-07-27 18:14 UTC, akinny commented on jwala-integration-test/src/test/resources/com/cerner/jwala/ui/selenium/configuration/generateAndDeployResources.feature
> +      | hostName   | usmlvv2cto0766       |
remove servername usmlvv2cto0766

2017-08-01 16:42 UTC, jmahmoodcc reviewed
Just some general comments:
 - We need a way configure the servers so that localhost isn't hard coded
 - We also need a way to configure the remote location so that things like D:/ctp aren't hard coded

2017-08-18 18:42 UTC, jeddcuison commented
Please see #151 and #157

2017-08-18 18:42 UTC, closed without merging