Cucumber Branch containing features- Search, Sort and Pagination
cerner/jwala pull request #147
Opened 2017-07-12 18:03 UTC by Sharvaribarve

This branch contains the automation tests for the features Search, Sort and Pagination

2017-07-14 18:30 UTC, akinny approved these changes

2017-07-27 05:12 UTC, jeddcuison requested changes
Please see  my comments

2017-07-27 05:12 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/configuration/ManagePaginationTest.java
> + * Created by SB053052 on 7/10/2017.
Change **all** SB053052  to your name since this is opensource

2017-07-27 05:12 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/ManagePaginationRunSteps.java
> +    JwalaUi jwalaUi;
Make this private

2017-07-27 05:12 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/ManagePaginationRunSteps.java
> +
Remove extra line

2017-07-27 05:12 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/ManagePaginationRunSteps.java
> +    @When("I click the next page button")
Is this step being use ? If so Shouldn't this be

    @When("^I click the next page button$")

The rest of the steps in this class don't have ^ $ as well

2017-07-27 05:12 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/ManageSearchRunSteps.java
> +
Remove extra spaces

2017-07-27 05:12 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/ManageSearchRunSteps.java
> +
Remove extra space

2017-07-27 05:12 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/ManageSortRunSteps.java
> +
Remove extra space

2017-07-27 05:12 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/ManageSortRunSteps.java
> +
Remove extra space

2017-07-27 05:12 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/ManageSortRunSteps.java
> +    @When("I click on the sort button of component \"(.*)\" with attribute \"(.*)\"$")
You forgot to put ^

2017-07-27 05:12 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/ManageSortRunSteps.java
> +    @When("I click on the sort button with attribute \"(.*)\"$")
You forgot to put ^

2017-07-27 05:12 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/ManageSortRunSteps.java
> +    @Then("I see first item \"(.*)\"$")
You forgot to put ^

2017-07-27 05:12 UTC, jeddcuison commented on jwala-integration-test/src/test/resources/com/cerner/jwala/ui/selenium/configuration/pagination.feature
> +
Where is When and Then ?

2017-07-27 05:12 UTC, jeddcuison commented on jwala-integration-test/src/test/resources/com/cerner/jwala/ui/selenium/configuration/pagination.feature
> +    Then I see the text "Page 2/2"
No When ? Instead of having 2 "Then" we should just concatenate with And e.g. Then And And And ...

2017-07-27 05:12 UTC, jeddcuison commented on jwala-integration-test/src/test/resources/com/cerner/jwala/ui/selenium/configuration/search.feature
> +    And I fill in the search field with "MM"
Where's When ?

2017-07-27 05:12 UTC, jeddcuison commented on jwala-integration-test/src/test/resources/com/cerner/jwala/ui/selenium/configuration/search.feature
> +    And I fill in the search field with "app"
Where's When ?

2017-07-27 05:12 UTC, jeddcuison commented on jwala-integration-test/src/test/resources/com/cerner/jwala/ui/selenium/configuration/search.feature
> +    And I fill in the search field with "ap"
Where's When ?

2017-07-27 05:12 UTC, jeddcuison commented on jwala-integration-test/src/test/resources/com/cerner/jwala/ui/selenium/configuration/search.feature
> +    And I fill in the search field with "my"
Where's When ?

2017-07-27 05:12 UTC, jeddcuison commented on jwala-integration-test/src/test/resources/com/cerner/jwala/ui/selenium/configuration/search.feature
> +  Scenario: Search within  jvms
Is this complete ?

2017-08-01 16:24 UTC, jmahmoodcc reviewed
Just a couple of general comments:
 - Please change the names of the JVMs, Web Servers, Web Apps, Groups, and Media to meaningful and unique names like jvm-1-test-name. In a lot of places there were just numbers or random letters used as names. When things fail this makes it a lot easier to trace and debug
 - Did we figure out a way to resolve things like server names and absolute paths yet? I see localhost and C:/ctp hard coded in a few places.

2017-08-03 15:16 UTC, jeddcuison reviewed
@jmahmoodcc, with regards to:

> Did we figure out a way to resolve things like server names and absolute paths yet? I see localhost and C:/ctp hard coded in a few places.

@Sharvaribarve changed the code and now gets some of the values from a properties file

2017-08-03 15:16 UTC, jeddcuison commented on jwala-integration-test/src/test/resources/com/cerner/jwala/ui/selenium/configuration/pagination.feature
> +      | webserverName      | 1WebServer          |
WebServer1, WebServer2, ... it more conventional. Judging from the name, attaching the WebServer part from the number required less effort hence the unconventional names. In addition the groups were renamed to Group1, Group2 etc, we should always be consistent on our naming convention.

2017-08-03 15:37 UTC, jeddcuison reviewed
Pass 1 complete please see comments, I'll do one more pass and build and run your tests before I tag my review as completed...

2017-08-03 15:37 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/SeleniumTestHelper.java
> +    private static final String JWALA_PROPERTIES = "selenium/jwala.properties";
Please commit a sample property file just like test.properties so that it is easier for developers to digest the purpose and contents of the file

2017-08-03 15:37 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/SeleniumTestHelper.java
> +    private static final String JWALA_PROPERTIES = "selenium/jwala.properties";
Can we make the property file name more descriptive like "parameters.properties" ?

2017-08-03 15:37 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/SeleniumTestHelper.java
> +    private static Properties jwalaProperties;
If you rename the properties file please don't forget to rename this one too

2017-08-03 15:37 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/CommonRunSteps.java
> +
Please remove extra line

2017-08-03 15:37 UTC, jeddcuison commented on jwala-integration-test/src/test/java/com/cerner/jwala/ui/selenium/steps/configuration/ManagePaginationRunSteps.java
> +    @When("^I select the dropdown of \"(.*)\" with option \"(.*)\"$")
Please put this before "Then" so that you code structure follows given-when-then

2017-08-03 15:37 UTC, jeddcuison commented on jwala-integration-test/src/test/resources/com/cerner/jwala/ui/selenium/configuration/search.feature
> +      | contextPath | \name1       |
use '/' and make the contextPath more descriptive e.g. "aContextPath1"  e.g.

    | contextPath | /name1 |

2017-08-06 20:07 UTC, jeddcuison commented
Already merged via pull request #150

2017-08-06 20:07 UTC, closed without merging