Postman add wait for asynchronous calls
cerner/jwala pull request #181
Opened 2017-11-15 22:28 UTC by rahulsayini

Add wait script between asynchronous calls for stop and start of webserver, jvm and group

2017-11-16 02:58 UTC, akinny requested changes

2017-11-16 02:58 UTC, akinny commented on jwala-integration-test/src/test/postman/jwala-collection.postman_collection.json
> +									"  while(curDate-date < millis);",
This is tight loop, I think it will cause 100% cpu utilization, did you check?

2017-11-16 14:06 UTC, jmahmoodcc requested changes
After the timeout expires you need to query the state of the JVM/Web Server to verify that it is started or stopped like the test intended

2017-12-07 19:05 UTC, jmahmoodcc requested changes
Using the promise and setTimeout is non-blocking, they won't actually pause the thread. See my comment for more details.

2017-12-07 19:05 UTC, jmahmoodcc commented on jwala-integration-test/src/test/postman/jwala-collection.postman_collection.json
> +									"return new Promise(resolve => setTimeout(resolve, millis))",
Promises and setTimeout are non-blocking - they execute asynchronously but they don't pause the thread. This solution won't have the intended delay that you're looking for.

See the answer here for more explanation:
https://stackoverflow.com/questions/36588775/are-javascript-promise-asynchronous

2017-12-11 14:40 UTC, akinny commented
Removing tight loop

2017-12-11 14:40 UTC, closed without merging