WIP: generate REST API documentation using Swagger
cerner/jwala pull request #194
Opened 2017-12-27 21:28 UTC by jmahmoodcc

Use the swagger-gradle-plugin (https://github.com/gigaSproule/swagger-gradle-plugin) to generate the REST API documentation
- TODO
-- add swagger annotation to all existing REST APIs
-- change localhost to server name
-- determine toc/jwala context path

2018-01-02 15:43 UTC, Sharvaribarve commented on jwala-webservices/src/main/java/com/cerner/jwala/ws/rest/v1/service/group/GroupServiceRest.java
> +    @ApiOperation(value = "Generate and deploy group webservers file",
I believe the description should be more verbose, the information provided can be taken from the method name itself

2018-01-04 21:20 UTC, akinny commented on jwala-webservices/build.gradle
> +            title = 'Jwala Tomcat Manager'
We need to change this title

2018-01-04 21:40 UTC, akinny commented on jwala-webservices/src/main/java/com/cerner/jwala/ws/rest/v1/service/jvm/JvmServiceRest.java
> +    @ApiOperation(value = "Create a JVM",
Can we add a note? something like, this will creates the jvm configuration within Jwala but only creates the jvm on the server upon generation

2018-01-04 21:42 UTC, akinny commented on jwala-webservices/src/main/java/com/cerner/jwala/ws/rest/v1/service/webserver/WebServerServiceRest.java
> +            response = WebServer.class
Same here, add a note stating it creates a webserver in Jwala DB, actual webserver on the server is created upon generation.

2018-01-04 21:44 UTC, akinny commented on jwala-webservices/src/main/java/com/cerner/jwala/ws/rest/v1/service/jvm/JvmServiceRest.java
> +    @ApiOperation(value = "Delete an existing JVM",
Can we make this more descriptive, what all is deleted, service, files,etc?

2018-01-04 21:48 UTC, akinny requested changes
Good team work! Minor changes

2018-01-19 18:25 UTC, akinny approved these changes

2018-01-24 14:36 UTC, merged