add postman tests to delete failed state JVM
cerner/jwala pull request #208
Opened 2018-09-17 02:40 UTC by rahulsayini

add postman tests to delete failed state JVM

2018-09-17 08:45 UTC, Karthik263 approved these changes

2018-09-18 19:09 UTC, jmahmoodcc requested changes
Just some minor changes.

2018-09-18 19:09 UTC, jmahmoodcc commented on jwala-integration-test/src/test/postman/jwala-collection.postman_collection.json
> +								"id": "bbc6d7d0-ceec-4469-926a-a12be613b4b4",
Remove these id attributes.
I don't think they break anything, but I didn't see them in any other pre-existing tests.

2018-09-18 19:09 UTC, jmahmoodcc commented on jwala-integration-test/src/test/postman/jwala-collection.postman_collection.json
> +							"raw": "{\"jvmName\":\"test-jvm-failed\",\"groupIds\":[{\"id\":10,\"groupId\":{{GroupId}}}],\"hostName\":\"{{host}}\",\"statusPath\":\"/tomcat-power.gif\",\"systemProperties\":\"\",\"httpPort\
Is it possible to not hard code the group ID?
We'll get errors in the test if we run them back-to-back and the group ID keeps incrementing.

2018-09-19 19:21 UTC, jmahmoodcc approved these changes

2018-09-19 19:21 UTC, merged