Incorporate backend validation of names for groups,web-servers and JVMs
cerner/jwala pull request #39
Opened 2017-03-29 16:24 UTC by Sharvaribarve

Before you contribute, please review these guidelines to help ensure a smooth process for everyone.

Thanks.

* Read [how to properly contribute to open source projects on Github][1].
* Fork the project.
* Use a feature branch.
* Write [good commit messages][2].
* Use the same coding conventions as the rest of the project.
* Commit locally and push to your fork until you are happy with your contribution.
* Make sure to add tests and verify all the tests are passing when merging upstream.
* Add an entry to the [Changelog][3] accordingly.
* Please add your name to the [CONTRIBUTORS.md][7] file. Adding your name to the [CONTRIBUTORS.md][7] file signifies agreement to all rights and reservations provided by the [License][4].
* [Squash related commits together][5].
* Open a [pull request][6].
* The pull request will be reviewed by the community and merged by the project committers.

[1]: http://gun.io/blog/how-to-github-fork-branch-and-pull-request
[2]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[3]: ./CHANGELOG.md
[4]: ./LICENSE
[5]: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
[6]: https://help.github.com/articles/using-pull-requests
[7]: ./CONTRIBUTORS.md

2017-03-29 16:34 UTC, PeterTeunissen commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/webserver/WebServerNameRule.java
> +        return name != null && !"".equals(name.trim()) && name.matches("[A-Za-z0-9._\\s-]+");
Is a name with a leading or trailing space really correct? Should we allow that?

2017-03-29 16:36 UTC, PeterTeunissen commented on jwala-common/src/test/java/com/cerner/jwala/common/rule/jvm/JvmNameRuleTest.java
> +        final String[] invalidNames = {"", "    ", null,"***$JVM","JVM123$"};
Add a test with a / and one with a \ in the name.  Those are file separators and would cause problems if we let those in.

2017-03-29 16:38 UTC, Sharvaribarve commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/webserver/WebServerNameRule.java
> +        return name != null && !"".equals(name.trim()) && name.matches("[A-Za-z0-9._\\s-]+");
Hi, they are allowed via the UI

2017-03-29 16:38 UTC, Sharvaribarve commented on jwala-common/src/test/java/com/cerner/jwala/common/rule/jvm/JvmNameRuleTest.java
> +        final String[] invalidNames = {"", "    ", null,"***$JVM","JVM123$"};
Sure, I will add those

2017-03-29 16:40 UTC, PeterTeunissen commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/webserver/WebServerNameRule.java
> +        return name != null && !"".equals(name.trim()) && name.matches("[A-Za-z0-9._\\s-]+");
But maybe that's a bug too...

2017-03-29 22:38 UTC, jmahmoodcc requested changes
looks good, just make some minor changes

2017-03-29 22:38 UTC, jmahmoodcc commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/group/GroupNameRule.java
> +        return name != null && !"".equals(name.trim()) && name.matches("[A-Za-z0-9._\\s-]+");
Please add a comment in the code to explain the characters allowed by the regular expression

2017-03-29 22:38 UTC, jmahmoodcc commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/jvm/JvmNameRule.java
> +        return name != null && !"".equals(name.trim()) && name.matches("[A-Za-z0-9._\\s-]+");
Add the comment explaining the regular expression for all of the classes

2017-03-29 22:38 UTC, jmahmoodcc commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/webserver/WebServerNameRule.java
> +        return name != null && !"".equals(name.trim()) && name.matches("[A-Za-z0-9._\\s-]+");
I agree, trailing and leading spaces can lead to maintainability issues with users in the long run. We should remove them from the name or flag the name as invalid.

2017-03-30 13:19 UTC, akinny approved these changes
Make changes requested by Jeff & Peter

2017-03-30 17:23 UTC, Sharvaribarve commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/group/GroupNameRule.java
> +        return name != null && !"".equals(name.trim()) && name.matches("[A-Za-z0-9._\\s-]+");
Done

2017-03-30 17:23 UTC, Sharvaribarve commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/jvm/JvmNameRule.java
> +        return name != null && !"".equals(name.trim()) && name.matches("[A-Za-z0-9._\\s-]+");
Done

2017-03-30 17:23 UTC, Sharvaribarve commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/webserver/WebServerNameRule.java
> +        return name != null && !"".equals(name.trim()) && name.matches("[A-Za-z0-9._\\s-]+");
Done

2017-03-30 17:24 UTC, Sharvaribarve commented on jwala-common/src/test/java/com/cerner/jwala/common/rule/jvm/JvmNameRuleTest.java
> +        final String[] invalidNames = {"", "    ", null,"***$JVM","JVM123$"};
Done

2017-04-03 14:57 UTC, PeterTeunissen commented on jwala-common/src/test/java/com/cerner/jwala/common/rule/webserver/WebServerNameRuleTest.java
> +        final String[] validNames = {"abc", "def", "a really long name","ws123","ws_123. "};
Names with spaces in them (or ending with them), should not be valid.

2017-04-04 12:54 UTC, akinny commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/group/GroupNameRule.java
> +    1)Checks for null
Use java doc style documentation, intelllij assits if you type /** and enter

2017-04-04 12:54 UTC, akinny approved these changes

2017-04-04 15:56 UTC, akinny approved these changes

2017-04-04 17:20 UTC, jmahmoodcc approved these changes

2017-04-04 17:20 UTC, merged