Fix performance issue for history
cerner/jwala pull request #40
Opened 2017-03-29 19:53 UTC by akinny

- added max limit to history
- made max history configurable
- default ui to 10,000 records
- Remove History from get Group & Webserver calls
- Sorry about the line endings in JpaGroupBuilder, removed getHistory

Before you contribute, please review these guidelines to help ensure a smooth process for everyone.

Thanks.

* Read [how to properly contribute to open source projects on Github][1].
* Fork the project.
* Use a feature branch.
* Write [good commit messages][2].
* Use the same coding conventions as the rest of the project.
* Commit locally and push to your fork until you are happy with your contribution.
* Make sure to add tests and verify all the tests are passing when merging upstream.
* Add an entry to the [Changelog][3] accordingly.
* Please add your name to the [CONTRIBUTORS.md][7] file. Adding your name to the [CONTRIBUTORS.md][7] file signifies agreement to all rights and reservations provided by the [License][4].
* [Squash related commits together][5].
* Open a [pull request][6].
* The pull request will be reviewed by the community and merged by the project committers.

[1]: http://gun.io/blog/how-to-github-fork-branch-and-pull-request
[2]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[3]: ./CHANGELOG.md
[4]: ./LICENSE
[5]: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
[6]: https://help.github.com/articles/using-pull-requests
[7]: ./CONTRIBUTORS.md

2017-03-29 21:10 UTC, PeterTeunissen approved these changes
ok

2017-03-29 22:50 UTC, jmahmoodcc requested changes
looks good, I would just change the name of the property and associate the numRecs variable in the UI to the vars.properties using ApplicationPropertySourceDefinition

2017-03-29 22:50 UTC, jmahmoodcc commented on jwala-common/src/main/java/com/cerner/jwala/common/properties/PropertyKeys.java
> +    MAX_JWALA_HISTORY("max.jwala.history");
Can we standardize that all of the properties specifically for jwala start with jwala?
So this property key would change to "jwala.max.history".

2017-03-29 22:50 UTC, jmahmoodcc commented on jwala-webapp/src/main/webapp/resources/js/react/group-operations/CommandStatusWidget.js
> +        this.props.numofRec=0;
You can add the max.jwala.history property to ApplicationPropertySourceDefinition and that way it gets read from vars.properties and applied in the UI

2017-03-30 12:53 UTC, akinny commented on jwala-webapp/src/main/webapp/resources/js/react/group-operations/CommandStatusWidget.js
> +        this.props.numofRec=0;
done!

2017-03-30 13:16 UTC, akinny commented on jwala-common/src/main/java/com/cerner/jwala/common/properties/PropertyKeys.java
> +    MAX_JWALA_HISTORY("max.jwala.history");
I renamed it

2017-04-03 16:37 UTC, jmahmoodcc approved these changes

2017-04-03 16:37 UTC, merged