check for existing associations before remove of media
cerner/jwala pull request #44
Opened 2017-03-31 13:41 UTC by rahulsayini

2017-03-31 15:13 UTC, PeterTeunissen commented on jwala-services/src/main/java/com/cerner/jwala/service/media/impl/MediaServiceImpl.java
> +            if (jvm.getJdkMedia().getName().equals(name)) {
Should this check be changed to ignore case?

2017-03-31 15:15 UTC, PeterTeunissen commented on jwala-webapp/src/main/webapp/resources/js/jwala/v1/service/mediaService.js
> +        return serviceFoundation.del("v1.0/media/" + encodeURIComponent(name), "json", caughtCallback);
I'm not a UI expert at all..... but you changed from .promisedDel to .del     is that OK? Check with Jed/Jeff ?

2017-03-31 15:15 UTC, PeterTeunissen reviewed
Leave a comment

2017-04-04 07:51 UTC, jeddcuison requested changes
Revert back to promisedDel for deleteMedia

2017-04-04 07:51 UTC, jeddcuison commented on jwala-webapp/src/main/webapp/resources/js/jwala/v1/service/mediaService.js
> +        return serviceFoundation.del("v1.0/media/" + encodeURIComponent(name), "json", caughtCallback);
Peter is correct going forward we should be using promisedDel since it is more straight forward and avoids "callback hell" - http://callbackhell.com/. We will be removing the regular methods once it is confirmed that we're not using them anymore.

In addition, the UI might not work properly with regards to error handling since the code using this service is written to use promises caught

    confirmDeleteCallback: function() {
        var self = this;
        ServiceFactory.getMediaService().deleteMedia(this.state.selectedMedia["str-name"]).then(function(response){
            self.refs.confirmDeleteMediaDlg.close();
            self.loadTableData(function(){
                self.state.selectedMedia = null;
            });
        }).caught(function(response){
            $.errorAlert(response);
        });
    }

2017-04-04 07:51 UTC, jeddcuison commented on jwala-services/src/main/java/com/cerner/jwala/service/media/impl/MediaServiceImpl.java
> +                throw new MediaServiceException(MessageFormat
Please avoid redundancy, this can be rewritten as

    final String msg = MessageFormat.format("The media {0} cannot be deleted because it is associated with a JVM or JVMs");
    LOGGER.error(msg);
    throw new MediaServiceException(msg);

Also please take note I changed the message a bit to make it more concise

2017-04-04 07:51 UTC, jeddcuison commented on jwala-services/src/main/java/com/cerner/jwala/service/media/impl/MediaServiceImpl.java
> +    private void checkForExistingAssociationsBeforeRemove(String name) {
Since this method just checks for JVM association, just name it as checkForJvmAssociation then while you're at it can you put java doc so that it's easy for people to see that it throws an exception when the check fails.

2017-04-04 12:46 UTC, akinny commented on jwala-services/src/main/java/com/cerner/jwala/service/media/impl/MediaServiceImpl.java
> +            if (jvm.getJdkMedia().getName().equalsIgnoreCase(name)) {
Since we allow null in jdkmedia, it might throw NPE. change it to 
name.equalsIgnoreCase(jvm.getJdkMedia().getName())

2017-04-04 12:51 UTC, akinny commented on jwala-services/src/main/java/com/cerner/jwala/service/media/impl/MediaServiceImpl.java
> +        checkForExistingAssociationsBeforeRemove(name);
I would make checkForExistingAssociationsBeforeRemove(name) return a boolean and throw an exception if true[may be rename to associationExists(name)], else remove it. This way we can reuse this method

2017-04-04 13:37 UTC, rahulsayini commented on jwala-services/src/main/java/com/cerner/jwala/service/media/impl/MediaServiceImpl.java
> +            if (jvm.getJdkMedia().getName().equalsIgnoreCase(name)) {
done

2017-04-04 13:37 UTC, rahulsayini commented on jwala-services/src/main/java/com/cerner/jwala/service/media/impl/MediaServiceImpl.java
> +    private void checkForExistingAssociationsBeforeRemove(String name) {
done

2017-04-04 13:38 UTC, rahulsayini commented on jwala-webapp/src/main/webapp/resources/js/jwala/v1/service/mediaService.js
> +        return serviceFoundation.del("v1.0/media/" + encodeURIComponent(name), "json", caughtCallback);
done

2017-04-04 15:53 UTC, merged