Added backend validation for length of group names
cerner/jwala pull request #53
Opened 2017-04-04 17:08 UTC by Sharvaribarve

Before you contribute, please review these guidelines to help ensure a smooth process for everyone.

Thanks.

* Read [how to properly contribute to open source projects on Github][1].
* Fork the project.
* Use a feature branch.
* Write [good commit messages][2].
* Use the same coding conventions as the rest of the project.
* Commit locally and push to your fork until you are happy with your contribution.
* Make sure to add tests and verify all the tests are passing when merging upstream.
* Add an entry to the [Changelog][3] accordingly.
* Please add your name to the [CONTRIBUTORS.md][7] file. Adding your name to the [CONTRIBUTORS.md][7] file signifies agreement to all rights and reservations provided by the [License][4].
* [Squash related commits together][5].
* Open a [pull request][6].
* The pull request will be reviewed by the community and merged by the project committers.

[1]: http://gun.io/blog/how-to-github-fork-branch-and-pull-request
[2]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[3]: ./CHANGELOG.md
[4]: ./LICENSE
[5]: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
[6]: https://help.github.com/articles/using-pull-requests
[7]: ./CONTRIBUTORS.md

2017-04-05 14:51 UTC, PeterTeunissen commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/group/GroupNameRule.java
> +    public boolean isValid() {return name != null && !"".equals(name.trim()) && !name.matches(".*[\\s]$") && !name.matches("^[\\s].*") && name.matches("[A-Za-z0-9._\\s-]+");
All the three rules (WebServer, Group and JVM have the same pattern. Can you push this to the ValidNameRule baseclass?

2017-04-05 14:53 UTC, PeterTeunissen requested changes
When a class extends a baseclass it indirectly implements all the interfaces of that class. So the Group, Jvm and Webserver classes do not need to mention that they implement Rule.

2017-04-05 14:54 UTC, PeterTeunissen commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/group/GroupNameRule.java
> +    public boolean isValid() {return name != null && !"".equals(name.trim()) && !name.matches(".*[\\s]$") && !name.matches("^[\\s].*") && name.matches("[A-Za-z0-9._\\s-]+");
Why is this a one-liner? (but that's a personal pref...)

2017-04-05 14:56 UTC, PeterTeunissen commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/group/GroupNameRule.java
> +        if(!isValidLength()){
use a space after the if and a space after the last ):
if (!isValidLength()) {

2017-04-05 14:56 UTC, PeterTeunissen commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/group/GroupNameRule.java
> +    public boolean isValidLength(){return name.length()<256;}
Same thing: why a one-liner? And fix spacing.

2017-04-05 15:07 UTC, Sharvaribarve commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/group/GroupNameRule.java
> +    public boolean isValid() {return name != null && !"".equals(name.trim()) && !name.matches(".*[\\s]$") && !name.matches("^[\\s].*") && name.matches("[A-Za-z0-9._\\s-]+");
Hi ValidNameRule is extended by other classes, like application which do not follow the same rules, application can contain "/", hence I overrid the methods in the subclasses.

2017-04-05 15:10 UTC, jeddcuison commented
Why are there so many commits ? Did you base off master ?

2017-04-05 15:17 UTC, jeddcuison requested changes
Please double check the test for long names it seems to me that it will always pass

2017-04-05 15:38 UTC, Sharvaribarve commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/group/GroupNameRule.java
> +        if(!isValidLength()){
Sure will do it

2017-04-05 15:38 UTC, Sharvaribarve commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/group/GroupNameRule.java
> +    public boolean isValidLength(){return name.length()<256;}
Sure will do it

2017-04-05 15:41 UTC, Sharvaribarve commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/group/GroupNameRule.java
> +    public boolean isValidLength(){return name.length()<256;}
Ok will change that

2017-04-06 01:48 UTC, LinHungWu requested changes
Soarian Financial always create group/webserver/jvms with - (dash), please at least allow (dash) in the rule.

2017-04-06 01:52 UTC, LinHungWu approved these changes

2017-04-06 01:53 UTC, LinHungWu commented
never mind, I saw the code now, i always dash and dot.

2017-04-06 20:02 UTC, jmahmoodcc requested changes

2017-04-06 20:02 UTC, jmahmoodcc commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/group/GroupNameRule.java
> +    protected MessageResponseStatus getMessageResponseGroupLengthStatus() { return FaultType.GROUP_NAME_TOO_LONG; }
Rename to something simpler, the return type is already MessageResponseStatus so no need to repeat it in the method name. Something like, getLongNameStatus().

Also, where is this method called from? FaultType is a public enum, do we really need a method wrapped around it?

2017-04-06 20:02 UTC, jmahmoodcc commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/group/GroupNameRule.java
> +        return name != null && !"".equals(name.trim()) && !name.matches(".*[\\s]$") && !name.matches("^[\\s].*") && name.matches("[A-Za-z0-9._\\s-]+");
I'd prefer this broken up across multiple lines - same thing for the other classes.

Also, is it possible to place this in a single method in the super class? It looks like the rule is the same across all of the classes.

2017-04-06 20:02 UTC, jmahmoodcc commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/group/GroupNameRule.java
> +        return name.length() < 256;
Make a constant in the super class for 256 and name it something like MAX_NAME_LENGTH

2017-04-06 20:42 UTC, Sharvaribarve commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/group/GroupNameRule.java
> +    protected MessageResponseStatus getMessageResponseGroupLengthStatus() { return FaultType.GROUP_NAME_TOO_LONG; }
Hi sure, I will rename it to something shorter, I did it because it was done similarly in invalid group name.

2017-04-06 20:43 UTC, Sharvaribarve commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/group/GroupNameRule.java
> +        return name != null && !"".equals(name.trim()) && !name.matches(".*[\\s]$") && !name.matches("^[\\s].*") && name.matches("[A-Za-z0-9._\\s-]+");
Hi. I can break it up, but there are other classes which inherit the rule but do not follow the same rule as groups like application.

2017-04-06 20:43 UTC, Sharvaribarve commented on jwala-common/src/main/java/com/cerner/jwala/common/rule/group/GroupNameRule.java
> +        return name.length() < 256;
Yeah done

2017-04-07 18:47 UTC, jmahmoodcc requested changes
Please create a special character name rule

2017-04-07 20:45 UTC, jmahmoodcc approved these changes

2017-04-07 21:06 UTC, merged