notify the UI that a web server was generated
cerner/jwala pull request #69
Opened 2017-04-10 17:21 UTC by jmahmoodcc

After generating a web server from the Operations tab, the state of the web server does not get updated from NEW to STOPPED. This causes problems when trying to start the web server from the UI immediately after generating.

The fix is to send the state update to the UI immediately after completing the web server generation.

2017-04-10 18:50 UTC, akinny approved these changes

2017-04-10 18:59 UTC, jeddcuison requested changes
Message is sent 2x on ping since it uses WebServerService update.

2017-04-10 18:59 UTC, jeddcuison commented on jwala-services/src/main/java/com/cerner/jwala/service/webserver/impl/WebServerServiceImpl.java
> +        messagingTemplate.convertAndSend(topicServerStates, new CurrentState<>(id, state, DateTime.now(), StateType.WEB_SERVER));
The WebServerStateSetterWorker setState sends a message to the UI already via the MessageService. If we put this here, the message will always be sent 2x. Can we put this after generation ? When we set the state to STOPPED ? In addition "updateState" in my opinion should just update the persistence layer and the hasmap, it's up to the client service to do notifications.

2017-04-10 19:00 UTC, jeddcuison commented on jwala-services/src/main/java/com/cerner/jwala/service/webserver/impl/WebServerServiceImpl.java
> +import org.springframework.messaging.simp.SimpMessagingTemplate;
In case we need to send a message, can we just use the MessagingService instead ?

2017-04-10 19:42 UTC, jmahmoodcc commented on jwala-services/src/main/java/com/cerner/jwala/service/webserver/impl/WebServerServiceImpl.java
> +        messagingTemplate.convertAndSend(topicServerStates, new CurrentState<>(id, state, DateTime.now(), StateType.WEB_SERVER));
Good catch! Making the changes now ...

2017-04-10 22:41 UTC, jeddcuison approved these changes
Looks good, I just have a few comments - minor ones, if it's not too much hassle can you look it ? Anyways you can merge it whether you did the comments or not. :)

2017-04-10 22:41 UTC, jeddcuison commented on jwala-webservices/src/main/java/com/cerner/jwala/ws/rest/v1/service/webserver/impl/WebServerServiceRestImpl.java
> +    SimpMessagingServiceImpl simpleMessagingService;
Can this be private ? Can we use the interface instead ? e.g. MessagingService

2017-04-11 02:10 UTC, jmahmoodcc commented on jwala-webservices/src/main/java/com/cerner/jwala/ws/rest/v1/service/webserver/impl/WebServerServiceRestImpl.java
> +    SimpMessagingServiceImpl simpleMessagingService;
Done

2017-04-11 02:24 UTC, merged