History logging of resources at web app
cerner/jwala pull request #79
Opened 2017-04-17 17:56 UTC by Sharvaribarve

Added history statement for deploying of resources at webapp level
Before you contribute, please review these guidelines to help ensure a smooth process for everyone.

Thanks.

* Read [how to properly contribute to open source projects on Github][1].
* Fork the project.
* Use a feature branch.
* Write [good commit messages][2].
* Use the same coding conventions as the rest of the project.
* Commit locally and push to your fork until you are happy with your contribution.
* Make sure to add tests and verify all the tests are passing when merging upstream.
* Add an entry to the [Changelog][3] accordingly.
* Please add your name to the [CONTRIBUTORS.md][7] file. Adding your name to the [CONTRIBUTORS.md][7] file signifies agreement to all rights and reservations provided by the [License][4].
* [Squash related commits together][5].
* Open a [pull request][6].
* The pull request will be reviewed by the community and merged by the project committers.

[1]: http://gun.io/blog/how-to-github-fork-branch-and-pull-request
[2]: http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[3]: ./CHANGELOG.md
[4]: ./LICENSE
[5]: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
[6]: https://help.github.com/articles/using-pull-requests
[7]: ./CONTRIBUTORS.md

2017-04-17 18:31 UTC, PeterTeunissen commented on jwala-services/src/main/java/com/cerner/jwala/service/app/impl/ApplicationServiceImpl.java
> +            historyFacadeService.write("", jvm.getGroups(), "Generating and Deploying \"" + appName + "\" resources", EventType.USER_ACTION_INFO, user.getId());
Can we get a more detailed message than just a generic one? Can we get one log entry for each webapp resource that we generate?

2017-04-17 18:31 UTC, PeterTeunissen requested changes
Can we get a more detailed message than just a generic one? Can we get one log entry for each webapp resource that we generate?

2017-04-19 15:57 UTC, jmahmoodcc requested changes
Making the change in this 1 location only covers a single scenario - deploying a Web App resource that is associated with a JVM.
We would want this change for all possible paths of deploying a Web App resource. That includes doing a generation of the Web App from the Operations tab, and deploying any Web App resource from the Resources tab.

2017-04-19 15:57 UTC, jmahmoodcc commented on jwala-services/src/main/java/com/cerner/jwala/service/app/impl/ApplicationServiceImpl.java
> +            historyFacadeService.write("", group, "Generating and Deploying resource files in webapp\"" + appName + "\" resources", EventType.USER_ACTION_INFO, user.getId());
Pass in the hostname for the first parameter instead of an empty string

2017-04-19 15:57 UTC, jmahmoodcc commented on jwala-services/src/main/java/com/cerner/jwala/service/app/impl/ApplicationServiceImpl.java
> +            historyFacadeService.write("", group, "Generating and Deploying resource files in webapp\"" + appName + "\" resources", EventType.USER_ACTION_INFO, user.getId());
Also, add the resource name to the message

2017-05-04 14:40 UTC, jeddcuison reviewed
I noticed that the last commit in this branch is "Merge branch 'master' of https://github.com/cerner/jwala into ResourcesHistory". The problem that I have with it is that the commit only contains changes from master. Was it manually merged by picking master changes and putting it into the branch ? Anyways the cleaner way of doing it is like this Merge branch 'master' of https://github.com/cerner/jwala into ResourcesHistory

2017-05-04 14:40 UTC, jeddcuison commented on jwala-webservices/src/main/java/com/cerner/jwala/ws/rest/v1/service/group/impl/GroupServiceRestImpl.java
> +                    historyFacadeService.write(hostName, group, "Deploying application resource "+resourceIdentifier.resourceName+" via operations", EventType.USER_ACTION_INFO, aUser.getUser().getId(
To be consistent with the rest of the code please don't forget to put spaces in between string concatenation e.g. 
     
    // instead of
    "Deploy application resource "+resourceIdentifier.resourceName+" via operations" 

    // should be
    "Deploy application resource " + resourceIdentifier.resourceName + " via operations"

2017-05-04 14:50 UTC, jmahmoodcc requested changes
Make sure an empty string is not sent in for the hostname when writing the history message

2017-05-04 14:50 UTC, jmahmoodcc commented on jwala-webservices/src/main/java/com/cerner/jwala/ws/rest/v1/service/app/impl/ApplicationServiceRestImpl.java
> +        historyFacadeService.write("", groupService.getGroup(groupName), "Deploying application resource " + resourceTemplateName + " via resources tab", EventType.USER_ACTION_INFO, authUser.getUser(
I would change the message to not say "via resources tab"

2017-05-04 14:50 UTC, jmahmoodcc commented on jwala-webservices/src/main/java/com/cerner/jwala/ws/rest/v1/service/app/impl/ApplicationServiceRestImpl.java
> +        historyFacadeService.write("", groupService.getGroup(groupName), "Deploying application resource " + resourceTemplateName + " via resources tab", EventType.USER_ACTION_INFO, authUser.getUser(
We shouldn't be passing an empty string for the hostname parameter. It looks like this needs to be moved into the service layer so the hostname is accessible for each individual deployment.

2017-05-04 14:50 UTC, jmahmoodcc commented on jwala-webservices/src/main/java/com/cerner/jwala/ws/rest/v1/service/group/impl/GroupServiceRestImpl.java
> +                    historyFacadeService.write("", group, "Deploying application resource "+resourceIdentifier.resourceName+" via operations to all hosts", EventType.USER_ACTION_INFO, aUser.getUser()
Again, don't send an empty string for the hostname parameter. You'll have to move this historyFacadeService.write into the performGroupAppDeployToHosts method and get the hostname from each JVM in the group.

2017-05-09 12:11 UTC, akinny commented on jwala-webservices/src/main/java/com/cerner/jwala/ws/rest/v1/service/app/impl/ApplicationServiceRestImpl.java
> +    private HistoryFacadeService historyFacadeService;
Can you remove this import, if this is not used?

2017-05-09 14:31 UTC, jmahmoodcc commented on jwala-webservices/src/main/java/com/cerner/jwala/ws/rest/v1/service/app/impl/ApplicationServiceRestImpl.java
> +    private HistoryFacadeService historyFacadeService;
+1

2017-05-09 14:41 UTC, jmahmoodcc requested changes
Some minor changes: remove the unused historyFacadeService in the ApplicationServiceRestImpl, and clean up some of the messages in the GroupServiceRestImpl

2017-05-09 14:41 UTC, jmahmoodcc commented on jwala-webservices/src/main/java/com/cerner/jwala/ws/rest/v1/service/group/impl/GroupServiceRestImpl.java
> +                historyFacadeService.write(hostName, group, "Deploying " + fileName + " to all JVMS in the group ", EventType.USER_ACTION_INFO, aUser.getUser().getId());
Change the message to say the resource is only being deployed to the JVMs on the specified host. The comment on line 703 is actually wrong, this clause will only deploy the resource to all the JVMs on a host - I would fix the comment on line 703 as well.

2017-05-09 14:41 UTC, jmahmoodcc commented on jwala-webservices/src/main/java/com/cerner/jwala/ws/rest/v1/service/group/impl/GroupServiceRestImpl.java
> +                    performGroupAppDeployToHosts(groupName, fileName, appName, metaData.isHotDeploy(), aUser);
This is where the resource is deployed to all JVMs in a group. Write a message here to the history stating the resource is being deployed to all JVMs in the group.

2017-05-10 21:52 UTC, jmahmoodcc approved these changes

2017-05-22 15:41 UTC, LinHungWu approved these changes

2017-05-22 18:04 UTC, merged