Error Message on clicking show details should display detailed error message instead of [object object]
cerner/jwala pull request #96
Opened 2017-05-09 15:04 UTC by Sharvaribarve

In case, the validation of resource file fails, the show details button on clicking displays [object object], this has been changed to display detailed error message.

2017-05-09 15:22 UTC, jmahmoodcc requested changes
Looks good, just clean up the formatting please (the indenting is off)

2017-05-09 20:29 UTC, jeddcuison requested changes
In lieu of Sharvari's findings that the details are the same as the message content displayed by the error dialog, the solution as discussed with the team is just to display the message. My bad I did not see this coming, the details section is supposed to be for stacktrace details. Please revert the changes and just omit the content parameter in $.errorAlert. By not providing the content, errorAlert is smart enough not to display the details button. Thanks!

2017-05-10 09:50 UTC, jeddcuison requested changes
Almost there, 2 additional comments, after those are addressed then we're good to go

2017-05-10 09:50 UTC, jeddcuison commented on jwala-webapp/src/main/webapp/resources/js/react/ResourcePane.js
> +        $.errorAlert(ResourcePane.parseDetailedErrorMsg(response, ResourcePane.DEFAULT_DEPLOY_ERR_MSG), "");
Please revert to:

    $.errorAlert(ResourcePane.parseDetailedErrorMsg(response, ResourcePane.DEFAULT_DEPLOY_ERR_MSG), "", undefined, response.responseJSON.content);

2017-05-10 09:50 UTC, jeddcuison commented on jwala-webapp/src/main/webapp/resources/js/error-alert.js
> +            if (content && content !== "" && Array.isArray(content)) {
Please remove unnecessary content validation, this will do 

    if (Array.isArray(content)) {
        ...
    }

2017-05-10 19:18 UTC, jeddcuison reviewed
The last change looks good. Can you write a selenium test for this ?

2017-05-12 14:25 UTC, jmahmoodcc approved these changes

2017-05-22 15:36 UTC, LinHungWu approved these changes

2017-05-22 18:06 UTC, merged